### ISSUE TITLE
mismatch in name of installation folder

### ISSUE THREAD

**Issue by robinzigmond** [vivithemage/do-wp#32]
When you publish a site, it looks for a directory called public_html, and flags an error if it doesn't find it. So if your local site uses a different name for this wordpress root folder, you have to rename it before publishing.

This is inconsistent with how the installation process works - it names this folder as whatever you enter in the Site Url field (which is also used for the database name). As a result, if you install your local site with this tool, and then later publish it, you'll have to rename it manually. It's no big deal, but it seems annoying and unnecessary.

It would be easy for the installation to simply name it public_html, and I don't see any problem with doing so (without having tested it yet!). Just wondering if you have any thoughts on it.

**Comment by vivithemage** [comment]
Yes absolutely. Please go ahead.
