### ISSUE TITLE
Install - Database creation fails if there is an existing database

### ISSUE THREAD

**Issue by vivithemage** [vivithemage/do-wp#5]
The database name is based on the hostname. So what would need to be done is a check to ensure the database does not already exist. If it does, flag an error.

**Comment by vivithemage** [comment]
Are the errors still occurring or did that one get sorted?

Thanks,
Reza

**Comment by robinzigmond** [comment]
Hi Reza,

No, I haven't looked at this one yet. (But I'll try to get it done today, I don't think it should be too hard.) The comments above are only there because I erroneously referenced this issue in a commit message, when it was supposed to be issue 15 (the phpmyadmin one).
